# Generated by Django 6.0.3 on 2026-04-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_item_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
