# Generated by Django 6.0.3 on 2026-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_sales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(default='Completed', editable=False, max_length=20),
        ),
    ]
