# Generated by Django 6.0.3 on 2026-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_alter_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
    ]
