# Generated by Django 6.0.3 on 2026-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_alter_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
